export const DUMMY_ACTION = 'DUMMY_ACTION';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'ADD_TO_PLAYLIST';