export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS';
export const CHANGE_CURRENT_TRACK = 'CHANGE_CURRENT_TRACK';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_TO_PLAYLIST';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
export const SAVE_PLAYLIST_TO_DISK = 'SAVE_PLAYLIST_TO_DISK';
export const LOAD_PLAYLIST_FROM_DISK = 'LOAD_PLAYLIST_FROM_DISK';
export const CHANGE_REPEAT_MODE = 'CHANGE_REPEAT_MODE';
export const CHANGE_SHUFFLE_MODE = 'CHANGE_SHUFFLE_MODE';

export const FETCH_NEW_LIST_REQUEST = 'FETCH_NEW_LIST_REQUEST';
export const FETCH_NEW_LIST_SUCCESS = 'FETCH_NEW_LIST_SUCCESS';
export const FETCH_NEW_LIST_FAILURE = 'FETCH_NEW_LIST_FAILURE';

export const FETCH_POPULAR_LIST_REQUEST = 'FETCH_POPULAR_LIST_REQUEST';
export const FETCH_POPULAR_LIST_SUCCESS = 'FETCH_POPULAR_LIST_SUCCESS';
export const FETCH_POPULAR_LIST_FAILURE = 'FETCH_POPULAR_LIST_FAILURE';

export const FETCH_MENTOR_PICK_REQUEST = 'FETCH_MENTOR_PICK_REQUEST';
export const FETCH_MENTOR_PICK_SUCCESS = 'FETCH_MENTOR_PICK_SUCCESS';
export const FETCH_MENTOR_PICK_FAILURE = 'FETCH_MENTOR_PICK_FAILURE';

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const UPDATE_USER = 'UPDATE_USER';
